"""empty message

Revision ID: c1d56476c674
Revises: 
Create Date: 2018-07-08 20:23:04.762097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d56476c674'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=True)
    op.drop_column('words', 'translation_3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('translation_3', sa.VARCHAR(length=5000), nullable=True))
    op.drop_index(op.f('ix_words_word'), table_name='words')
    # ### end Alembic commands ###
